CREATE TABLE IF NOT EXISTS sensor_latest_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id UUID NOT NULL REFERENCES iot_devices (id),
    sensor_type_id UUID NOT NULL REFERENCES sensor_types (id),
    zone_id UUID REFERENCES farm_zones (id),
    reading_time TIMESTAMPTZ NOT NULL,
    reading_value DOUBLE PRECISION NOT NULL,
    quality_status VARCHAR(30),
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uk_sensor_latest_readings_device_sensor_type'
    ) THEN
        ALTER TABLE sensor_latest_readings
            ADD CONSTRAINT uk_sensor_latest_readings_device_sensor_type
                UNIQUE (device_id, sensor_type_id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_sensor_latest_readings_zone_sensor_type
    ON sensor_latest_readings (zone_id, sensor_type_id);

CREATE INDEX IF NOT EXISTS idx_sensor_latest_readings_device_reading_time_desc
    ON sensor_latest_readings (device_id, reading_time DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uq_sensor_reading_agg_5m_device_sensor_zone_bucket
    ON sensor_reading_agg_5m (device_id, sensor_type_id, zone_id, bucket_start, bucket_end)
    WHERE zone_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_sensor_reading_agg_5m_device_sensor_bucket_null_zone
    ON sensor_reading_agg_5m (device_id, sensor_type_id, bucket_start, bucket_end)
    WHERE zone_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_sensor_reading_agg_5m_device_sensor_bucket_desc
    ON sensor_reading_agg_5m (device_id, sensor_type_id, bucket_start DESC);

CREATE INDEX IF NOT EXISTS idx_sensor_reading_agg_5m_zone_sensor_bucket_desc
    ON sensor_reading_agg_5m (zone_id, sensor_type_id, bucket_start DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uq_sensor_reading_agg_1h_device_sensor_zone_bucket
    ON sensor_reading_agg_1h (device_id, sensor_type_id, zone_id, bucket_start, bucket_end)
    WHERE zone_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_sensor_reading_agg_1h_device_sensor_bucket_null_zone
    ON sensor_reading_agg_1h (device_id, sensor_type_id, bucket_start, bucket_end)
    WHERE zone_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_sensor_reading_agg_1h_device_sensor_bucket_desc
    ON sensor_reading_agg_1h (device_id, sensor_type_id, bucket_start DESC);

CREATE INDEX IF NOT EXISTS idx_sensor_reading_agg_1h_zone_sensor_bucket_desc
    ON sensor_reading_agg_1h (zone_id, sensor_type_id, bucket_start DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uq_sensor_reading_agg_1d_device_sensor_zone_bucket
    ON sensor_reading_agg_1d (device_id, sensor_type_id, zone_id, bucket_start, bucket_end)
    WHERE zone_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_sensor_reading_agg_1d_device_sensor_bucket_null_zone
    ON sensor_reading_agg_1d (device_id, sensor_type_id, bucket_start, bucket_end)
    WHERE zone_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_sensor_reading_agg_1d_device_sensor_bucket_desc
    ON sensor_reading_agg_1d (device_id, sensor_type_id, bucket_start DESC);

CREATE INDEX IF NOT EXISTS idx_sensor_reading_agg_1d_zone_sensor_bucket_desc
    ON sensor_reading_agg_1d (zone_id, sensor_type_id, bucket_start DESC);

CREATE INDEX IF NOT EXISTS idx_iot_devices_farm_plot_status
    ON iot_devices (farm_plot_id, status);

CREATE INDEX IF NOT EXISTS idx_iot_devices_zone_status
    ON iot_devices (zone_id, status);

CREATE INDEX IF NOT EXISTS idx_iot_devices_owner_user_id
    ON iot_devices (owner_user_id);

CREATE INDEX IF NOT EXISTS idx_alert_events_zone_status_created_at_desc
    ON alert_events (zone_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_alert_events_device_status_created_at_desc
    ON alert_events (device_id, status, created_at DESC);
