apiVersion: apps/v1
kind: Deployment
metadata:
  name: leafy-search-service
  namespace: leafy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      nodeSelector:
        node-type: search-ai
      containers:
        - name: search-service
          image: leafy-search-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGODB_DATABASE_SEARCH
              valueFrom:
                secretKeyRef:
                  name: leafy-db-secrets
                  key: MONGODB_DATABASE_SEARCH
          envFrom:
            - configMapRef:
                name: leafy-common-config
            - secretRef:
                name: leafy-common-secrets
          ports:
            - containerPort: 8088
          resources:
            requests:
              memory: 512Mi
              cpu: 300m
            limits:
              memory: 1536Mi
              cpu: 1000m
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8088
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8088
            initialDelaySeconds: 90
            periodSeconds: 30
            failureThreshold: 3
