package com.leafy.plantmanagementservice.model;

import com.leafy.common.model.BaseModel;
import com.leafy.plantmanagementservice.model.enums.TreatmentStatus;
import lombok.*;
import lombok.experimental.FieldDefaults;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.FieldType;
import org.springframework.data.mongodb.core.mapping.MongoId;

import java.util.List;

/**
 * MongoDB document representing a disease treatment plan generated by the RAG service.
 *
 * <p>One Plan produces a set of {@link PlantEvent} documents via
 * {@code PlantEventService.createEvents()} — their IDs are recorded in
 * {@link #plantEventIds} for traceability.
 *
 * <p>Field names mirror the RAG service {@code Plan} Pydantic model and the
 * {@code PlantEventCreateRequest} DTO so that data can flow from the AI pipeline to
 * the calendar with zero field mapping.
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Document(collection = "plans")
@FieldDefaults(level = AccessLevel.PRIVATE)
public class Plan extends BaseModel {

    @MongoId(FieldType.OBJECT_ID)
    String id;

    // ── Source tracking ───────────────────────────────────────────────────────

    /** ID of the user who triggered the plan via the RAG chat endpoint. */
    String userId;

    /**
     * {@code planId} UUID from the RAG service {@code PlanDoc}.
     * Allows the AI service to later look up which Java plan corresponds to its record.
     */
    String ragPlanId;

    /** Original natural-language question the user sent to the RAG service. */
    String question;

    /** Evidence source used by the AI plan generator: websearch or documents. */
    String source;

    // ── Plant / Farm scope ────────────────────────────────────────────────────

    @Indexed
    String plantId;

    @Indexed
    String farmPlotId;

    @Indexed
    String farmZoneId;

    // ── Diagnosis ─────────────────────────────────────────────────────────────

    /** Custom name for the plan */
    String planName;

    /** Full name of the identified disease, e.g. "Coffee Leaf Rust (Hemileia vastatrix)". */
    String diseaseName;

    /** LLM confidence in this diagnosis (0.0 = uncertain, 1.0 = certain). */
    Double confidenceScore;

    /** Severity: {@code LOW}, {@code MEDIUM}, or {@code HIGH}. */
    String severityLevel;

    /** Time sensitivity: {@code IMMEDIATE}, {@code HIGH}, or {@code NORMAL}. */
    String urgency;

    // ── Plan metadata ─────────────────────────────────────────────────────────

    /** All tools, materials, and chemicals needed to execute the full plan. */
    List<String> requiredInputs;

    /** Critical safety notes applicable to the whole plan (PPE, PHI, disposal). */
    List<String> safetyWarnings;

    /** Visual or measurable signs that the treatment is working. */
    String successIndicators;

    /** Estimated total cost for the entire plan (chemicals, tools, labour). */
    String estimatedCost;

    // ── Generated events ──────────────────────────────────────────────────────

    /**
     * MongoDB {@link PlantEvent} IDs bulk-created from this plan's schedule.
     * Populated after {@code PlantEventService.createEvents()} completes.
     */
    List<String> plantEventIds;

    // ── Lifecycle ─────────────────────────────────────────────────────────────

    /** Current status of the treatment plan. Defaults to {@link TreatmentStatus#PENDING}. */
    @Builder.Default
    TreatmentStatus status = TreatmentStatus.PENDING;

    /** Number of times this plan has been applied to plants/farms. */
    @Builder.Default
    Integer applyCount = 0;
}
