spring:
  application:
    name: api-gateway
  messages:
    basename: i18n/messages,i18n/gateway-messages
    encoding: UTF-8
  config:
    import: configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
      fail-fast: false
      retry:
        max-attempts: 10
        initial-interval: 1000
        max-interval: 10000
        multiplier: 2.0
      request-connect-timeout: 5000
      request-read-timeout: 10000
  kafka:
    enabled: false

cors:
  allowed-origins: http://localhost:3000,http://localhost:5173,http://192.168.100.55:5173,http://192.168.100.55:3000,https://leafy-fe.vercel.app,https://leafy-fe.vercel.app/login,http://lehao.io.vn,https://lehao.io.vn,http://www.lehao.io.vn,https://www.lehao.io.vn

app:
  services:
    auth-service:
      url: ${AUTH_SERVICE_URL:http://leafy-auth-service:8089}
