from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
from typing import Optional, Any, List, Dict

from app.agents.rag_agent import rag_app

router = APIRouter()


class ChatRequest(BaseModel):
    question: str = Field(
        ...,
        description="The natural-language question to send to the RAG pipeline.",
        examples=["What are the common diseases affecting corn crops?"],
        min_length=1,
        max_length=2000,
    )
    user_id: Optional[str] = Field(
        None,
        description=(
            "Optional user identifier. When provided, the vector store query is "
            "filtered to include only chunks belonging to this user, enabling "
            "per-user document isolation."
        ),
        examples=["usr_001"],
    )
    language: Optional[str] = Field(
        "English",
        description="The desired language for the output.",
        examples=["Vietnamese", "Spanish", "English"],
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "question": "What are the common diseases affecting corn crops?",
                "user_id": "usr_001",
                "language": "English",
            }
        }
    }


class ChatResponse(BaseModel):
    answer: str = Field(
        ...,
        description="Grounded answer generated by the LLM, backed by retrieved document chunks.",
        examples=["Common corn diseases include Gray Leaf Spot, Northern Corn Leaf Blight, and Common Rust …"],
    )
    documents: Optional[List[Any]] = Field(
        None,
        description=(
            "List of source document chunks used to ground the answer. "
            "Each item contains the chunk text and associated metadata (filename, page, score …)."
        ),
    )
    treatment_plan: Optional[Dict[str, Any]] = Field(
        None,
        description="Structured treatment plan if a planning request was made.",
    )
    plant_id: Optional[str] = Field(
        None,
        description="Plant ID associated with the treatment plan.",
    )
    web_search_results: Optional[List[Dict[str, Any]]] = Field(
        None,
        description="List of external web search results used to ground the answer (if the deep path was taken).",
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "answer": "Common corn diseases include Gray Leaf Spot, Northern Corn Leaf Blight, and Common Rust.",
                "documents": [
                    {
                        "page_content": "Gray Leaf Spot is caused by the fungus Cercospora zeae-maydis …",
                        "metadata": {"source": "plant-disease-report.pdf", "page": 3},
                    }
                ],
                "treatment_plan": {
                    "schedule": [
                        {
                            "eventType": "DISEASE_DETECTED",
                            "note": "Initial diagnosis of Coffee Leaf Rust",
                            "description": "Visual confirmation of orange-yellow powdery lesions on the underside of coffee leaves, characteristic of Coffee Leaf Rust."
                        }
                    ]
                },
                "plant_id": "plant_123",
            }
        }
    }


@router.post(
    "/chat",
    response_model=ChatResponse,
    summary="Ask a question via the RAG pipeline",
    responses={
        200: {"description": "Grounded answer successfully generated."},
        500: {"description": "Internal error during graph execution — see `detail` for the exception message."},
    },
)
async def chat(request: ChatRequest):
    """
    Submit a natural-language question and receive a **grounded answer** produced
    by the LangGraph RAG state-machine.

    **Pipeline stages (executed in order):**
    1. **Router** — decides whether a fast or deep retrieval path is needed.
    2. **Hybrid Search** — combines dense vector search with BM25 sparse retrieval.
    3. **Reranker** — cross-encoder reranking to surface the most relevant chunks.
    4. **Generation** — the LLM (Gemini / GPT) synthesises the final answer.
    5. **Self-correction** — if the answer is not grounded, the query is transformed
       and the graph retries (up to `max_retries` times).

    Set `user_id` to restrict retrieval to documents uploaded by that user.
    """
    try:
        initial_state = {
            "question": request.question,
            "retry_count": 0,
            "language": request.language,
        }
        final_state = await rag_app.ainvoke(initial_state)

        return ChatResponse(
            answer=final_state.get("generation", "I could not generate an answer."),
            documents=final_state.get("documents", []),
            treatment_plan=final_state.get("generated_plan"),
            plant_id=final_state.get("plant_id"),
            web_search_results=final_state.get("web_search_results", []),
        )
    except Exception as e:
        # In production, log error to LangSmith/Sentry
        print(f"Error in chat endpoint: {e}")
        raise HTTPException(status_code=500, detail=str(e))

