apiVersion: apps/v1
kind: Deployment
metadata:
  name: leafy-auth-service
  namespace: leafy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      nodeSelector:
        node-type: app
      containers:
        - name: auth-service
          image: 383704034208.dkr.ecr.ap-southeast-1.amazonaws.com/leafy/auth-service:latest
          imagePullPolicy: Always
          env:
            - name: MONGODB_DATABASE_AUTH
              valueFrom:
                secretKeyRef:
                  name: leafy-db-secrets
                  key: MONGODB_DATABASE_AUTH
          envFrom:
            - configMapRef:
                name: leafy-common-config
            - secretRef:
                name: leafy-common-secrets
          ports:
            - containerPort: 8089
              name: http
          resources:
            requests:
              memory: 512Mi
              cpu: 200m
            limits:
              memory: 1536Mi
              cpu: 1000m
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8089
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
