apiVersion: apps/v1
kind: Deployment
metadata:
  name: leafy-file-service
  namespace: leafy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      nodeSelector:
        node-type: app
      initContainers:
        - name: wait-for-config-server
          image: busybox
          command:
            - sh
            - -c
            - |
              until wget -qO- http://leafy-config-server:8888/actuator/health/readiness 2>/dev/null | grep -q '"status":"UP"'; do
                echo "Waiting for config-server..."
                sleep 5
              done
              echo "Config server is UP"
      containers:
        - name: file-service
          image: 383704034208.dkr.ecr.ap-southeast-1.amazonaws.com/leafy/file-service:latest
          imagePullPolicy: Always
          env:
            - name: MONGODB_DATABASE_FILE
              valueFrom:
                secretKeyRef:
                  name: leafy-db-secrets
                  key: MONGODB_DATABASE_FILE
          envFrom:
            - configMapRef:
                name: leafy-common-config
            - secretRef:
                name: leafy-common-secrets
          ports:
            - containerPort: 8084
          resources:
            requests:
              memory: 512Mi
              cpu: 150m
            limits:
              memory: 1536Mi
              cpu: 1000m
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
