apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-logs-pvc
  namespace: leafy
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ebs-gp3
  resources:
    requests:
      storage: 1Gi
