apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: leafy-api
  region: ap-southeast-1

vpc:
  id: "vpc-05b31b1731dfc6cdb"
  subnets:
    public:
      ap-southeast-1a: { id: "subnet-0cdb1e35d7b62c34c" }
      ap-southeast-1b: { id: "subnet-0cd1a044b8a25ea60" }
    private:
      ap-southeast-1a: { id: "subnet-0cb156938c5ea9153" }
      ap-southeast-1b: { id: "subnet-0efe0988022be8d95" }

managedNodeGroups:
  - name: ng-0-messaging
    instanceType: c7i-flex.large
    desiredCapacity: 1
    privateNetworking: true
    labels: { node-type: messaging }

  - name: ng-1-data
    instanceType: c7i-flex.large
    desiredCapacity: 1
    privateNetworking: true
    labels: { node-type: data }

  - name: ng-2-app
    instanceType: m7i-flex.large
    desiredCapacity: 1
    privateNetworking: true
    labels: { node-type: app }

  - name: ng-3-search-ai
    instanceType: m7i-flex.large
    desiredCapacity: 1
    privateNetworking: true
    labels: { node-type: search-ai }