apiVersion: apps/v1
kind: Deployment
metadata:
  name: leafy-socket-service
  namespace: leafy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket-service
  template:
    metadata:
      labels:
        app: socket-service
    spec:
      nodeSelector:
        node-type: app
      containers:
        - name: socket-service
          image: 383704034208.dkr.ecr.ap-southeast-1.amazonaws.com/leafy/socket-service:latest
          imagePullPolicy: Always
          env:
            - name: MONGODB_DATABASE_SOCKET
              valueFrom:
                secretKeyRef:
                  name: leafy-db-secrets
                  key: MONGODB_DATABASE_SOCKET
          envFrom:
            - configMapRef:
                name: leafy-common-config
            - secretRef:
                name: leafy-common-secrets
          ports:
            - containerPort: 8093
          resources:
            requests:
              memory: 512Mi
              cpu: 300m
            limits:
              memory: 1536Mi
              cpu: 1000m
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8093
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8093
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
