apiVersion: apps/v1
kind: Deployment
metadata:
  name: leafy-message-service
  namespace: leafy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      nodeSelector:
        node-type: app
      containers:
        - name: message-service
          image: 383704034208.dkr.ecr.ap-southeast-1.amazonaws.com/leafy/message-service:latest
          imagePullPolicy: Always
          env:
            - name: MONGODB_DATABASE_MESSAGES
              valueFrom:
                secretKeyRef:
                  name: leafy-db-secrets
                  key: MONGODB_DATABASE_MESSAGES
          envFrom:
            - configMapRef:
                name: leafy-common-config
            - secretRef:
                name: leafy-common-secrets
          ports:
            - containerPort: 8092
          resources:
            requests:
              memory: 512Mi
              cpu: 150m
            limits:
              memory: 1536Mi
              cpu: 1000m
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8092
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
