apiVersion: apps/v1
kind: Deployment
metadata:
  name: leafy-disease-detection-service
  namespace: leafy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: disease-detection-service
  template:
    metadata:
      labels:
        app: disease-detection-service
    spec:
      nodeSelector:
        node-type: search-ai
      containers:
        - name: disease-detection-service
          image: 383704034208.dkr.ecr.ap-southeast-1.amazonaws.com/leafy/disease-detection-service:latest
          imagePullPolicy: Always
          env:
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: leafy-db-secrets
                  key: MONGODB_DATABASE_DISEASE
          envFrom:
            - configMapRef:
                name: leafy-common-config
            - configMapRef:
                name: disease-detection-config
            - secretRef:
                name: leafy-common-secrets
          ports:
            - containerPort: 8090
          resources:
            requests:
              memory: 2048Mi
              cpu: 500m
            limits:
              memory: 2048Mi
              cpu: 500m
          readinessProbe:
            httpGet:
              path: /health
              port: 8090
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
