apiVersion: v1
kind: Service
metadata:
  name: leafy-disease-detection-service
  namespace: leafy
spec:
  ports:
    - port: 8096
      targetPort: 8096
  selector:
    app: disease-detection-service
