package com.leafy.plantmanagementservice.dto.request.plant;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PositiveOrZero;
import com.leafy.plantmanagementservice.model.enums.PlantStatus;
import lombok.*;
import lombok.experimental.FieldDefaults;

import java.time.LocalDateTime;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@FieldDefaults(level = AccessLevel.PRIVATE)
public class PlantCreateRequest {

    // Ignored on create — auto-generated by the service
    String plantNumber;

    @NotNull(message = "Plant status is required")
    PlantStatus plantStatus;

    String nickName;
    String tagCode;
    String batchNumber;
    String sourceType;
    String motherPlantId;

    LocalDateTime plantingDate;
    LocalDateTime germinationDate;
    LocalDateTime actualHarvestDate;

    @PositiveOrZero(message = "Total yield must be positive or zero")
    Double totalYieldKg;

    @NotBlank(message = "Species ID is required")
    String speciesId;

    @NotBlank(message = "Farm plot ID is required")
    String farmPlotId;

    String farmZoneId;
}
