apiVersion: apps/v1
kind: Deployment
metadata:
  name: leafy-api-gateway
  namespace: leafy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      nodeSelector:
        node-type: app
      containers:
        - name: api-gateway
          image: 383704034208.dkr.ecr.ap-southeast-1.amazonaws.com/leafy/api-gateway:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: leafy-common-config
            - secretRef:
                name: leafy-common-secrets
          ports:
            - containerPort: 8060
          resources:
            requests:
              memory: 512Mi
              cpu: 300m
            limits:
              memory: 1536Mi
              cpu: 1000m
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8060
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8060
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
