apiVersion: v1
kind: Service
metadata:
  name: leafy-mongodb
  namespace: leafy
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
  selector:
    app: mongodb
  clusterIP: None
