[PARSER]
    Name                    datalog
    Format                  regex
    Regex                   ^(?<time>\d{4}-\d{2}-\d{2}\s{1,2}\d{2}:\d{2}:\d{2}\.\d{3})\s+(?<level>\w+)\s+(?<pid>\d+)\s+---\s+\[(?<thread>[^\]]+)\]\s+(?<class>[^\s]+)\s+:\s+(?<message>.*)$
    Time_Key                time
    Time_Format             %Y-%m-%d %H:%M:%S.%L
    Time_Keep               On
    Types                  level:string pid:integer

[PARSER]
    Name                    json
    Format                  json
    Time_Key                time
    Time_Format             %Y-%m-%dT%H:%M:%S.%LZ
    Time_Keep               On

[PARSER]
    Name                    docker
    Format                  json
    Time_Key                time
    Time_Format             %Y-%m-%dT%H:%M:%S.%LZ
