from pydantic import BaseModel, Field
from typing import Literal, Optional, Any, List, Dict


class ChatRequest(BaseModel):
    question: str = Field(
        ...,
        description="The natural-language question to send to the RAG pipeline.",
        examples=["What are the common diseases affecting corn crops?"],
        min_length=1,
        max_length=8000,  # Increased to support long plan-generation directives
    )
    language: Optional[str] = Field(
        "English",
        description="The desired language for the output.",
        examples=["Vietnamese", "Spanish", "English"],
    )
    thread_id: Optional[str] = Field(
        None,
        description=(
            "Conversation thread identifier used for multi-turn memory. "
            "Pass the same value on follow-up questions to continue the same session. "
            "Omit (or set to null) to start a fresh conversation."
        ),
        examples=["user-42-session-abc123"],
    )
    farm_plot_id: Optional[str] = Field(
        None,
        description=(
            "Farm plot ID to use for IoT environmental context. "
            "When provided, the pipeline resolves the zone and fetches sensor readings "
            "even if no plant ID is mentioned in the question."
        ),
        examples=["abc123def456abc123def456"],
    )
    farm_zone_id: Optional[str] = Field(
        None,
        description=(
            "Farm zone ID to use for IoT environmental context. "
            "Takes priority over farm_plot_id when both are provided. "
            "Directly fetches sensor readings for the given zone."
        ),
        examples=["abc123def456abc123def456"],
    )
    plant_id: Optional[str] = Field(
        None,
        description="Plant ID to associate with the treatment plan.",
        examples=["plant123"],
    )
    route: Optional[Literal["auto", "fast", "deep", "planner"]] = Field(
        "auto",
        description=(
            "Route selection override. "
            "'auto' (default) lets the router decide automatically based on question content. "
            "'fast' forces Gemini Flash without web search. "
            "'deep' forces web search + Gemini Pro. "
            "'planner' forces the treatment plan generation path."
        ),
        examples=["auto", "fast", "deep", "planner"],
    )
    search_query: Optional[str] = Field(
        None,
        description=(
            "Optional dedicated Qdrant retrieval query, decoupled from `question`. "
            "When provided, hybrid_search uses this string for vector/BM25 search "
            "instead of `question`. Useful when `question` is in English but the "
            "knowledge base is in Vietnamese (e.g. pass the disease name in Vietnamese "
            "so the retrieval is accurate while generation stays in the target language)."
        ),
        examples=["bệnh rỉ sắt cà phê điều trị phòng trừ"],
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "question": "What are the common diseases affecting corn crops?",
                "language": "English",
                "thread_id": "user-42-session-abc123",
                "farm_plot_id": "abc123def456abc123def456",
                "farm_zone_id": None,
                "plant_id": "plant123",
                "route": "auto",
            }
        }
    }


class ChatResponse(BaseModel):
    answer: str = Field(
        ...,
        description="Grounded answer generated by the LLM, backed by retrieved document chunks.",
    )
    thread_id: str = Field(
        ...,
        description="Conversation thread identifier. Pass this back on follow-up questions to continue the session.",
    )
    documents: Optional[List[Any]] = Field(
        None,
        description="Source document chunks used to ground the answer.",
    )
    plan: Optional[Dict[str, Any]] = Field(
        None,
        description="Structured treatment plan if a planning request was made.",
    )
    plant_id: Optional[str] = Field(
        None,
        description="Plant ID associated with the treatment plan.",
    )
    web_search_results: Optional[List[Dict[str, Any]]] = Field(
        None,
        description="External web search results used to ground the answer.",
    )
    saved_plan_id: Optional[str] = Field(
        None,
        description="MongoDB document ID of the saved Plan, if one was generated.",
    )
