from pydantic import BaseModel, Field
from typing import Optional, Any, List, Dict


class ChatRequest(BaseModel):
    question: str = Field(
        ...,
        description="The natural-language question to send to the RAG pipeline.",
        examples=["What are the common diseases affecting corn crops?"],
        min_length=1,
        max_length=2000,
    )
    language: Optional[str] = Field(
        "English",
        description="The desired language for the output.",
        examples=["Vietnamese", "Spanish", "English"],
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "question": "What are the common diseases affecting corn crops?",
                "language": "English",
            }
        }
    }


class ChatResponse(BaseModel):
    answer: str = Field(
        ...,
        description="Grounded answer generated by the LLM, backed by retrieved document chunks.",
    )
    documents: Optional[List[Any]] = Field(
        None,
        description="Source document chunks used to ground the answer.",
    )
    treatment_plan: Optional[Dict[str, Any]] = Field(
        None,
        description="Structured treatment plan if a planning request was made.",
    )
    plant_id: Optional[str] = Field(
        None,
        description="Plant ID associated with the treatment plan.",
    )
    web_search_results: Optional[List[Dict[str, Any]]] = Field(
        None,
        description="External web search results used to ground the answer.",
    )
    saved_plan_id: Optional[str] = Field(
        None,
        description="MongoDB document ID of the saved TreatmentPlan, if one was generated.",
    )
