apiVersion: apps/v1
kind: Deployment
metadata:
  name: leafy-discovery-server
  namespace: leafy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      nodeSelector:
        node-type: app
      containers:
        - name: discovery-server
          image: ${ECR_REGISTRY}/leafy-discovery-server:${IMAGE_TAG}
          ports:
            - containerPort: 8761
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 1024Mi
              cpu: 1000m
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8761
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8761
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
