apiVersion: apps/v1
kind: Deployment
metadata:
  name: leafy-rag-service
  namespace: leafy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-service
  template:
    metadata:
      labels:
        app: rag-service
    spec:
      nodeSelector:
        node-type: search-ai
      initContainers:
        - name: wait-for-infra
          image: busybox
          command: ['sh', '-c', 'until nc -z leafy-discovery-server 8761 && nc -z leafy-config-server 8888; do if ! nc -z leafy-discovery-server 8761; then echo "Waiting for leafy-discovery-server:8761..."; fi; if ! nc -z leafy-config-server 8888; then echo "Waiting for leafy-config-server:8888..."; fi; sleep 5; done; echo "Infrastructure services are UP!";']
      containers:
        - name: rag-service
          image: 574802241242.dkr.ecr.ap-southeast-1.amazonaws.com/leafy/rag-service:latest
          imagePullPolicy: Always
          env:
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: leafy-db-secrets
                  key: MONGODB_DATABASE_RAG
          envFrom:
            - configMapRef:
                name: leafy-common-config
            - configMapRef:
                name: rag-config
            - secretRef:
                name: leafy-common-secrets
          ports:
            - containerPort: 8199
          resources:
            requests:
              memory: 1024Mi
              cpu: 300m
            limits:
              memory: 2048Mi
              cpu: 400m
          readinessProbe:
            httpGet:
              path: /health
              port: 8199
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
