apiVersion: apps/v1
kind: Deployment
metadata:
  name: leafy-plant-management-service
  namespace: leafy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plant-management-service
  template:
    metadata:
      labels:
        app: plant-management-service
    spec:
      nodeSelector:
        node-type: app
      containers:
        - name: plant-management-service
          image: leafy-plant-management-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGODB_DATABASE_PLANT
              valueFrom:
                secretKeyRef:
                  name: leafy-db-secrets
                  key: MONGODB_DATABASE_PLANT
          envFrom:
            - configMapRef:
                name: leafy-common-config
            - secretRef:
                name: leafy-common-secrets
          ports:
            - containerPort: 8086
              name: http
          resources:
            requests:
              memory: 512Mi
              cpu: 300m
            limits:
              memory: 1536Mi
              cpu: 1000m
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8086
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
