spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        encrypt:
          enabled: false

  # Disable Kafka for infrastructure service
  kafka:
    enabled: false

server:
  port: ${SERVER_PORT_CONFIG}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME}

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.config: DEBUG
