server:
  port: ${SERVER_PORT_FILE}

spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE_FILE}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      authentication-database: admin
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

aws:
  s3:
    bucket: leafy-meida-storage
  region: ap-southeast-1

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    defaults:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true
