server:
  port: ${SERVER_PORT_MESSAGES:8092}

spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27018}
      database: ${MONGODB_DATABASE_MESSAGES:leafy_message}
      username: ${MONGODB_USERNAME:root}
      password: ${MONGODB_PASSWORD:rootpassword123}
      authentication-database: admin

leafy:
  security:
    gateway-auth:
      enabled: true
  frontend-url: ${FRONTEND_URL:https://leafy.com}


