server:
  port: ${SERVER_PORT_NOTIFICATION:}

spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE_NOTIFICATION}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      authentication-database: admin
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

bondhub:
  security:
    gateway-auth:
      enabled: true

brevo:
  api-key: ${BREVO_API_KEY:}
  default-sender-email: ${BREVO_SENDER_EMAIL:}
  default-sender-name: ${BREVO_SENDER_NAME:}
  enabled: ${BREVO_ENABLED:false}

notification:
  email:
    enabled: ${NOTIFICATION_EMAIL_ENABLED:false}
    from: ${NOTIFICATION_EMAIL_FROM:}
  sms:
    enabled: ${NOTIFICATION_SMS_ENABLED:from}
  push:
    enabled: ${NOTIFICATION_PUSH_ENABLED:true}
  kafka:
    topics:
      alertTriggered: iot.alert.triggered
      alertReady: iot.alert.ready

firebase:
  enabled: ${FIREBASE_ENABLED:true}
  configPath: ${FIREBASE_CONFIG_PATH:}
