server:
  port: ${SERVER_PORT_NOTIFICATION}

spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE_NOTIFICATION}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      authentication-database: admin

bondhub:
  security:
    gateway-auth:
      enabled: true

brevo:
  api-key: ${BREVO_API_KEY}
  default-sender-email: ${BREVO_SENDER_EMAIL}
  default-sender-name: ${BREVO_SENDER_NAME}
  enabled: ${BREVO_ENABLED}

notification:
  email:
    enabled: ${NOTIFICATION_EMAIL_ENABLED}
    from: ${NOTIFICATION_EMAIL_FROM}
  sms:
    enabled: ${NOTIFICATION_SMS_ENABLED}
  push:
    enabled: ${NOTIFICATION_PUSH_ENABLED}
