apiVersion: apps/v1
kind: Deployment
metadata:
  name: leafy-iot-metrics-collector-service
  namespace: leafy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-metrics-collector-service
  template:
    metadata:
      labels:
        app: iot-metrics-collector-service
    spec:
      nodeSelector:
        node-type: infra
      initContainers:
        - name: wait-for-infra
          image: busybox
          command: ['sh', '-c', 'until nc -z leafy-discovery-server 8761 && nc -z leafy-config-server 8888; do if ! nc -z leafy-discovery-server 8761; then echo "Waiting for leafy-discovery-server:8761..."; fi; if ! nc -z leafy-config-server 8888; then echo "Waiting for leafy-config-server:8888..."; fi; sleep 5; done; echo "Infrastructure services are UP!";']
      containers:
        - name: iot-metrics-collector-service
          image: 574802241242.dkr.ecr.ap-southeast-1.amazonaws.com/leafy/iot-metrics-collector-service:latest
          imagePullPolicy: Always
          env:
            - name: SERVER_IOT_PORT
              value: "8092"
            - name: DB_HOST
              value: "leafy-postgresql"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "leafy_iot_db"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: leafy-common-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: leafy-common-secrets
                  key: DB_PASSWORD
            - name: DISEASE_DETECTION_PREDICT_URL
              value: "http://leafy-disease-detection-service:8090/internal/diseases/predict"
          envFrom:
            - configMapRef:
                name: leafy-common-config
          ports:
            - containerPort: 8092
          resources:
            requests:
              memory: 512Mi
              cpu: 300m
            limits:
              memory: 1536Mi
              cpu: 1000m
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8092
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8092
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
