apiVersion: apps/v1
kind: Deployment
metadata:
  name: leafy-iot-metrics-collector-service
  namespace: leafy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-metrics-collector-service
  template:
    metadata:
      labels:
        app: iot-metrics-collector-service
    spec:
      nodeSelector:
        node-type: messaging
      initContainers:
        - name: wait-for-infra
          image: busybox
          command:
            - sh
            - -c
            - |
              until wget -qO- http://leafy-discovery-server:8761/actuator/health/readiness 2>/dev/null | grep -q '"status":"UP"'; do
                echo "Waiting for discovery-server..."
                sleep 5
              done
              until wget -qO- http://leafy-config-server:8888/actuator/health/readiness 2>/dev/null | grep -q '"status":"UP"'; do
                echo "Waiting for config-server..."
                sleep 5
              done
              echo "Infrastructure services are UP"
      containers:
        - name: iot-metrics-collector-service
          image: ${ECR_REGISTRY}/leafy-iot-metrics-collector-service:${IMAGE_TAG}
          env:
            - name: IMAGE_TAG
              value: latest
            - name: SERVER_IOT_PORT
              value: "8092"
            - name: DB_HOST
              value: "leafy-postgresql"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "leafy_iot_db"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: leafy-common-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: leafy-common-secrets
                  key: DB_PASSWORD
          envFrom:
            - configMapRef:
                name: leafy-common-config
          ports:
            - containerPort: 8092
          resources:
            requests:
              memory: 512Mi
              cpu: 300m
            limits:
              memory: 1536Mi
              cpu: 1000m
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8092
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8092
            initialDelaySeconds: 90
            periodSeconds: 30
            failureThreshold: 3
