apiVersion: v1
kind: Service
metadata:
  name: leafy-iot-metrics-collector-service
  namespace: leafy
spec:
  ports:
    - port: 8087
      targetPort: 8087
  selector:
    app: iot-metrics-collector-service
